//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbsenteDBEntities : DbContext
    {
        public AbsenteDBEntities()
            : base("name=AbsenteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsenteT> AbsenteT { get; set; }
        public virtual DbSet<DocsMotivareT> DocsMotivareT { get; set; }
        public virtual DbSet<EleviT> EleviT { get; set; }
        public virtual DbSet<MateriiT> MateriiT { get; set; }
        public virtual DbSet<SemestreT> SemestreT { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
