//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenteT
    {
        public int AbsentaID { get; set; }
        public int SemestrulFK { get; set; }
        public int ElevFK { get; set; }
        public int MateriaFK { get; set; }
        public System.DateTime Data { get; set; }
        public bool Motivata { get; set; }
    
        public virtual EleviT EleviT { get; set; }
        public virtual MateriiT MateriiT { get; set; }
        public virtual SemestreT SemestreT { get; set; }
    }
}
