//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocsMotivareT
    {
        public int DocMotivareID { get; set; }
        public int ElevFK { get; set; }
        public byte[] DocMotivare { get; set; }
        public System.DateTime DataStart { get; set; }
        public System.DateTime DataStop { get; set; }
    
        public virtual EleviT EleviT { get; set; }
    }
}
