//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EleviT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EleviT()
        {
            this.AbsenteT = new HashSet<AbsenteT>();
            this.DocsMotivareT = new HashSet<DocsMotivareT>();
        }

        public EleviT(string fullname)
        {
            this.AbsenteT = new HashSet<AbsenteT>();
            this.DocsMotivareT = new HashSet<DocsMotivareT>();
            Fullname = fullname;
        }

        public int ElevID { get; set; }
        public string Fullname { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenteT> AbsenteT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocsMotivareT> DocsMotivareT { get; set; }
    }
}
