//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriiT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MateriiT()
        {
            this.AbsenteT = new HashSet<AbsenteT>();
        }

        public MateriiT(string materie)
        {
            this.AbsenteT = new HashSet<AbsenteT>();
            Materia = materie;
        }

        public int MaterieID { get; set; }
        public string Materia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenteT> AbsenteT { get; set; }
    }
}
