//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenteAPP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestreT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemestreT()
        {
            this.AbsenteT = new HashSet<AbsenteT>();
        }

        public SemestreT(string semestru,string an,DateTime start,DateTime stop)
        {
            this.AbsenteT = new HashSet<AbsenteT>();
            Semestrul = semestru;
            Anul = an;
            DataStart = start;
            DataStop = stop;
        }

        public int SemestruID { get; set; }
        public string Semestrul { get; set; }
        public System.DateTime DataStart { get; set; }
        public System.DateTime DataStop { get; set; }
        public string Anul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenteT> AbsenteT { get; set; }
    }
}
